name: Test Git
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
jobs:
  my-job:
    name: check new versions
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun git.ts
