name: Issue Listener
on:
  issues:
    types: [opened]
permissions:
  issues: write
  contents: write
jobs:
  my-job:
    name: release from issue
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun issue_listeners.ts
