name: Test Git
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'Plotly version to add'
permissions:
  actions: write
  contents: write
jobs:
  my-job:
    name: print stuff
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INPUT_VERSION: ${{ inputs.version }}
      REPO: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun index.ts
