name: Test Julia
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
jobs:
  my-job:
    name: print stuff
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.event.repository.name }}
      OWNER: ${{ github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: julia-actions/setup-julia@v1
        with: 
          version: '1.9'
      - uses: julia-actions/cache@v1
      - run: bun install
      - run: echo "$OWNER, $(REPO)"
      - run: |
          echo "Owner: $(OWNER), Repo: $(REPO)"
